version: "3.9"
services:
  api:
    build: .
    ports:
      -  8000:8000
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      SECRET_KEY: "dk6m^0&nq=ra0=l8mtipgn#r6g90=)$jc@6@i+8trcsqn9%ke!"
    depends_on:
      - db
  db:
    image: postgres:15.2
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
    driver: local
