# Generated by Django 4.1.7 on 2023-03-01 22:50

import url_shortener.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField(unique=True)),
                ('shortened', models.CharField(default=url_shortener.utils.generate_short_url, max_length=20, unique=True)),
            ],
        ),
    ]
